"""Added name column

Revision ID: b97c4729a355
Revises: 
Create Date: 2022-04-12 11:01:20.763543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97c4729a355'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_column('user', 'date_added')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_added', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
